import type { PartDef } from "./types";

function dipPins(count: 8 | 14 | 16 | 20 | 24 | 28 | 40, labels: string[]): PartDef["pins"] {
  return labels.map((label, i) => ({
    id: String(i + 1),
    label,
    number: i + 1,
  }));
}

export const CATALOG: PartDef[] = [
  {
    id: "ne555",
    name: "NE555 timer",
    class: "dip",
    dipPins: 8,
    description: "Classic 8-pin timer. Pin 1 at the notch.",
    pins: dipPins(8, ["GND", "TRIG", "OUT", "RESET", "CTRL", "THRES", "DISCH", "VCC"]),
  },
  {
    id: "lm358",
    name: "LM358 dual op-amp",
    class: "dip",
    dipPins: 8,
    description: "Dual op-amp, single supply.",
    pins: dipPins(8, ["OUT A", "IN− A", "IN+ A", "GND", "IN+ B", "IN− B", "OUT B", "VCC"]),
  },
  {
    id: "lm7805",
    name: "7805 regulator",
    class: "power",
    description: "TO-220 5 V regulator. Place across three adjacent rows.",
    pins: [
      { id: "1", label: "IN", number: 1 },
      { id: "2", label: "GND", number: 2 },
      { id: "3", label: "OUT", number: 3 },
    ],
    defaultSpan: 2,
  },
  {
    id: "74hc595",
    name: "74HC595 shift register",
    class: "dip",
    dipPins: 16,
    description: "8-bit serial-in parallel-out.",
    pins: dipPins(16, [
      "QB",
      "QC",
      "QD",
      "QE",
      "QF",
      "QG",
      "QH",
      "GND",
      "QH'",
      "SRCLR",
      "SRCLK",
      "RCLK",
      "OE",
      "SER",
      "QA",
      "VCC",
    ]),
  },
  {
    id: "atmega328p",
    name: "ATmega328P",
    class: "dip",
    dipPins: 28,
    description: "DIP MCU used on Arduino Uno.",
    pins: dipPins(28, [
      "PC6",
      "PD0",
      "PD1",
      "PD2",
      "PD3",
      "PD4",
      "VCC",
      "GND",
      "PB6",
      "PB7",
      "PD5",
      "PD6",
      "PD7",
      "PB0",
      "PB1",
      "PB2",
      "PB3",
      "PB4",
      "PB5",
      "AVCC",
      "AREF",
      "GND",
      "PC0",
      "PC1",
      "PC2",
      "PC3",
      "PC4",
      "PC5",
    ]),
  },
  {
    id: "resistor",
    name: "Resistor",
    class: "passive",
    description: "Axial resistor. Set the value after placing.",
    pins: [
      { id: "a", label: "A" },
      { id: "b", label: "B" },
    ],
    defaultSpan: 4,
    color: "#c4a574",
  },
  {
    id: "ceramic-cap",
    name: "Ceramic capacitor",
    class: "passive",
    description: "Small decoupling or timing cap.",
    pins: [
      { id: "a", label: "A" },
      { id: "b", label: "B" },
    ],
    defaultSpan: 2,
    color: "#c9b896",
  },
  {
    id: "electrolytic",
    name: "Electrolytic capacitor",
    class: "passive",
    polar: true,
    description: "Polarized cap. Stripe marks the negative lead.",
    pins: [
      { id: "pos", label: "+" },
      { id: "neg", label: "−" },
    ],
    defaultSpan: 2,
    color: "#4a6b8a",
  },
  {
    id: "led",
    name: "LED",
    class: "led",
    polar: true,
    description: "Longer lead is anode (+). Flat side is cathode.",
    pins: [
      { id: "a", label: "A" },
      { id: "k", label: "K" },
    ],
    defaultSpan: 2,
    color: "#c45c4a",
  },
  {
    id: "diode",
    name: "1N4148 diode",
    class: "passive",
    polar: true,
    description: "Stripe marks the cathode.",
    pins: [
      { id: "a", label: "A" },
      { id: "k", label: "K" },
    ],
    defaultSpan: 3,
    color: "#2a2a2a",
  },
  {
    id: "npn",
    name: "2N2222 NPN",
    class: "passive",
    description: "TO-92, E-B-C when flat faces you (check your bag).",
    pins: [
      { id: "e", label: "E" },
      { id: "b", label: "B" },
      { id: "c", label: "C" },
    ],
    defaultSpan: 2,
  },
  {
    id: "button",
    name: "Tactile button",
    class: "button",
    description: "4-pin 6mm button. Opposite pins are common.",
    pins: [
      { id: "1", label: "1" },
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
    ],
    defaultSpan: 3,
  },
  {
    id: "slide-switch",
    name: "SPDT slide switch",
    class: "switch",
    description: "Three pins in a row. Center is common.",
    pins: [
      { id: "1", label: "A" },
      { id: "2", label: "COM" },
      { id: "3", label: "B" },
    ],
    defaultSpan: 2,
  },
  {
    id: "pot",
    name: "Trimmer pot",
    class: "passive",
    description: "10k trimmer. Three pins.",
    pins: [
      { id: "1", label: "CW" },
      { id: "2", label: "WIPER" },
      { id: "3", label: "CCW" },
    ],
    defaultSpan: 2,
  },
  {
    id: "photoresistor",
    name: "Photoresistor",
    class: "sensor",
    description: "LDR. Resistance falls with light.",
    pins: [
      { id: "a", label: "A" },
      { id: "b", label: "B" },
    ],
    defaultSpan: 3,
    color: "#c9a227",
  },
  {
    id: "tmp36",
    name: "TMP36 temperature",
    class: "sensor",
    description: "Analog temp sensor. +Vs, Vout, GND.",
    pins: [
      { id: "1", label: "+Vs" },
      { id: "2", label: "Vout" },
      { id: "3", label: "GND" },
    ],
    defaultSpan: 2,
  },
  {
    id: "dht22",
    name: "DHT22 humidity",
    class: "sensor",
    description: "4-pin module. Use 1, 2, 4 (leave 3 empty).",
    pins: [
      { id: "1", label: "VCC" },
      { id: "2", label: "DATA" },
      { id: "3", label: "NC" },
      { id: "4", label: "GND" },
    ],
    defaultSpan: 3,
  },
  {
    id: "hcsr04",
    name: "HC-SR04 ultrasonic",
    class: "module",
    description: "Off-board module. VCC, Trig, Echo, GND.",
    pins: [
      { id: "vcc", label: "VCC" },
      { id: "trig", label: "TRIG" },
      { id: "echo", label: "ECHO" },
      { id: "gnd", label: "GND" },
    ],
  },
  {
    id: "9v-snap",
    name: "9 V battery snap",
    class: "power",
    description: "Off-board clip. Red to +, black to −.",
    pins: [
      { id: "pos", label: "+" },
      { id: "neg", label: "−" },
    ],
  },
  {
    id: "barrel-jack",
    name: "Barrel jack",
    class: "module",
    description: "DC jack breakout. Center positive by convention.",
    pins: [
      { id: "pos", label: "+" },
      { id: "neg", label: "−" },
    ],
  },
  {
    id: "uno",
    name: "Arduino Uno",
    class: "module",
    description: "Off-board Uno. Wire headers to the breadboard.",
    pins: [
      { id: "5v", label: "5V" },
      { id: "gnd", label: "GND" },
      { id: "3v3", label: "3V3" },
      { id: "d2", label: "D2" },
      { id: "d3", label: "D3" },
      { id: "d4", label: "D4" },
      { id: "d5", label: "D5" },
      { id: "d13", label: "D13" },
      { id: "a0", label: "A0" },
    ],
  },
  {
    id: "nano",
    name: "Arduino Nano",
    class: "dip",
    dipPins: 28,
    description: "Nano seated across the gutter like a wide DIP.",
    pins: dipPins(28, [
      "D1",
      "D0",
      "RESET",
      "GND",
      "D2",
      "D3",
      "D4",
      "D5",
      "D6",
      "D7",
      "D8",
      "D9",
      "D10",
      "D11",
      "D12",
      "D13",
      "3V3",
      "AREF",
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "5V",
      "VIN",
    ]),
  },
  {
    id: "pico",
    name: "Raspberry Pi Pico",
    class: "module",
    description: "Off-board Pico. Bring 3V3, GND, and GPIOs over with Dupont wire.",
    pins: [
      { id: "3v3", label: "3V3" },
      { id: "gnd", label: "GND" },
      { id: "gp0", label: "GP0" },
      { id: "gp1", label: "GP1" },
      { id: "gp15", label: "GP15" },
      { id: "gp16", label: "GP16" },
    ],
  },
];

const BY_ID = new Map(CATALOG.map((p) => [p.id, p]));

export function getPart(id: string): PartDef | undefined {
  return BY_ID.get(id);
}

export function searchParts(query: string): PartDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  return CATALOG.filter(
    (p) =>
      p.id.includes(q) ||
      p.name.toLowerCase().includes(q) ||
      p.class.includes(q) ||
      p.description.toLowerCase().includes(q),
  );
}

export const CLASS_LABEL: Record<PartDef["class"], string> = {
  dip: "Chips",
  passive: "Passives",
  led: "LEDs",
  switch: "Switches",
  button: "Buttons",
  power: "Power",
  sensor: "Sensors",
  module: "Modules",
};
