import type { PartDef } from "./types.ts";

function dipPins(labels: string[]): PartDef["pins"] {
  return labels.map((label, i) => ({
    id: String(i + 1),
    label,
    number: i + 1,
  }));
}

function header(pins: string[]): PartDef["pins"] {
  return pins.map((label) => ({
    id: label.toLowerCase().replace(/[^a-z0-9]+/g, ""),
    label,
  }));
}

export const CATALOG: PartDef[] = [
  {
    id: "ne555",
    name: "NE555 timer",
    class: "dip",
    dipPins: 8,
    description: "Classic 8-pin timer. Pin 1 at the notch.",
    pins: dipPins(["GND", "TRIG", "OUT", "RESET", "CTRL", "THRES", "DISCH", "VCC"]),
  },
  {
    id: "lm358",
    name: "LM358 dual op-amp",
    class: "dip",
    dipPins: 8,
    description: "Dual op-amp, single supply.",
    pins: dipPins(["OUT A", "IN− A", "IN+ A", "GND", "IN+ B", "IN− B", "OUT B", "VCC"]),
  },
  {
    id: "lm7805",
    name: "7805 regulator",
    class: "power",
    description: "TO-220 5 V regulator. Place across three adjacent rows.",
    pins: [
      { id: "1", label: "IN", number: 1 },
      { id: "2", label: "GND", number: 2 },
      { id: "3", label: "OUT", number: 3 },
    ],
    defaultSpan: 2,
  },
  {
    id: "74hc595",
    name: "74HC595 shift register",
    class: "dip",
    dipPins: 16,
    description: "8-bit serial-in parallel-out.",
    pins: dipPins([
      "QB",
      "QC",
      "QD",
      "QE",
      "QF",
      "QG",
      "QH",
      "GND",
      "QH'",
      "SRCLR",
      "SRCLK",
      "RCLK",
      "OE",
      "SER",
      "QA",
      "VCC",
    ]),
  },
  {
    id: "atmega328p",
    name: "ATmega328P",
    class: "dip",
    dipPins: 28,
    description: "DIP MCU used on Arduino Uno.",
    pins: dipPins([
      "PC6",
      "PD0",
      "PD1",
      "PD2",
      "PD3",
      "PD4",
      "VCC",
      "GND",
      "PB6",
      "PB7",
      "PD5",
      "PD6",
      "PD7",
      "PB0",
      "PB1",
      "PB2",
      "PB3",
      "PB4",
      "PB5",
      "AVCC",
      "AREF",
      "GND",
      "PC0",
      "PC1",
      "PC2",
      "PC3",
      "PC4",
      "PC5",
    ]),
  },
  {
    id: "resistor",
    name: "Resistor",
    class: "passive",
    description: "Axial resistor. Set the value after placing.",
    pins: [
      { id: "a", label: "A" },
      { id: "b", label: "B" },
    ],
    defaultSpan: 4,
    color: "#c4a574",
  },
  {
    id: "ceramic-cap",
    name: "Ceramic capacitor",
    class: "passive",
    description: "Small decoupling or timing cap.",
    pins: [
      { id: "a", label: "A" },
      { id: "b", label: "B" },
    ],
    defaultSpan: 2,
    color: "#c9b896",
  },
  {
    id: "electrolytic",
    name: "Electrolytic capacitor",
    class: "passive",
    polar: true,
    description: "Polarized cap. Stripe marks the negative lead.",
    pins: [
      { id: "pos", label: "+" },
      { id: "neg", label: "−" },
    ],
    defaultSpan: 2,
    color: "#4a6b8a",
  },
  {
    id: "led",
    name: "LED",
    class: "led",
    polar: true,
    description: "Longer lead is anode (+). Flat side is cathode.",
    pins: [
      { id: "a", label: "A" },
      { id: "k", label: "K" },
    ],
    defaultSpan: 2,
    color: "#c45c4a",
  },
  {
    id: "diode",
    name: "1N4148 diode",
    class: "passive",
    polar: true,
    description: "Stripe marks the cathode.",
    pins: [
      { id: "a", label: "A" },
      { id: "k", label: "K" },
    ],
    defaultSpan: 3,
    color: "#2a2a2a",
  },
  {
    id: "npn",
    name: "2N2222 NPN",
    class: "passive",
    description: "TO-92, E-B-C when flat faces you (check your bag).",
    pins: [
      { id: "e", label: "E" },
      { id: "b", label: "B" },
      { id: "c", label: "C" },
    ],
    defaultSpan: 2,
  },
  {
    id: "button",
    name: "Tactile button",
    class: "button",
    description: "4-pin 6mm button. Opposite pins are common.",
    pins: [
      { id: "1", label: "1" },
      { id: "2", label: "2" },
      { id: "3", label: "3" },
      { id: "4", label: "4" },
    ],
    defaultSpan: 3,
  },
  {
    id: "slide-switch",
    name: "SPDT slide switch",
    class: "switch",
    description: "Three pins in a row. Center is common.",
    pins: [
      { id: "1", label: "A" },
      { id: "2", label: "COM" },
      { id: "3", label: "B" },
    ],
    defaultSpan: 2,
  },
  {
    id: "pot",
    name: "Trimmer pot",
    class: "passive",
    description: "10k trimmer. Three pins.",
    pins: [
      { id: "1", label: "CW" },
      { id: "2", label: "WIPER" },
      { id: "3", label: "CCW" },
    ],
    defaultSpan: 2,
  },
  {
    id: "photoresistor",
    name: "Photoresistor",
    class: "sensor",
    description: "LDR. Resistance falls with light.",
    pins: [
      { id: "a", label: "A" },
      { id: "b", label: "B" },
    ],
    defaultSpan: 3,
    color: "#c9a227",
  },
  {
    id: "tmp36",
    name: "TMP36 temperature",
    class: "sensor",
    description: "Analog temp sensor. +Vs, Vout, GND.",
    pins: [
      { id: "1", label: "+Vs" },
      { id: "2", label: "Vout" },
      { id: "3", label: "GND" },
    ],
    defaultSpan: 2,
  },
  {
    id: "dht22",
    name: "DHT22 humidity",
    class: "sensor",
    description: "4-pin module. Use 1, 2, 4 (leave 3 empty).",
    pins: [
      { id: "1", label: "VCC" },
      { id: "2", label: "DATA" },
      { id: "3", label: "NC" },
      { id: "4", label: "GND" },
    ],
    defaultSpan: 3,
  },
  {
    id: "hcsr04",
    name: "HC-SR04 ultrasonic",
    class: "module",
    description: "Off-board module. VCC, Trig, Echo, GND.",
    pins: [
      { id: "vcc", label: "VCC" },
      { id: "trig", label: "TRIG" },
      { id: "echo", label: "ECHO" },
      { id: "gnd", label: "GND" },
    ],
  },
  {
    id: "9v-snap",
    name: "9 V battery snap",
    class: "power",
    description: "Off-board clip. Red to +, black to −.",
    pins: [
      { id: "pos", label: "+" },
      { id: "neg", label: "−" },
    ],
  },
  {
    id: "barrel-jack",
    name: "Barrel jack",
    class: "module",
    description: "DC jack breakout. Center positive by convention.",
    pins: [
      { id: "pos", label: "+" },
      { id: "neg", label: "−" },
    ],
  },
  {
    id: "uno",
    name: "Arduino Uno",
    class: "module",
    description: "Off-board Uno R3. Jumper 5V, GND, and I/O over to the breadboard.",
    pins: header(["5V", "3V3", "GND", "VIN", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11", "D12", "D13", "A0", "A1", "A2", "A3", "A4", "A5"]),
  },
  {
    id: "mega",
    name: "Arduino Mega 2560",
    class: "module",
    description: "Off-board Mega. Same power pins as Uno, plus extra digital headers.",
    pins: header(["5V", "3V3", "GND", "VIN", "D2", "D3", "D4", "D5", "D10", "D13", "D20", "D21", "A0", "A1"]),
  },
  {
    id: "leonardo",
    name: "Arduino Leonardo",
    class: "module",
    description: "Off-board Leonardo. Native USB; pin names match the Uno headers.",
    pins: header(["5V", "3V3", "GND", "D2", "D3", "D4", "D5", "D6", "D7", "D13", "A0"]),
  },
  {
    id: "micro",
    name: "Arduino Micro",
    class: "module",
    description: "Off-board Micro. 5V ATmega32U4 in a small USB stick.",
    pins: header(["5V", "3V3", "GND", "D2", "D3", "D4", "D5", "D6", "D13", "A0"]),
  },
  {
    id: "nano",
    name: "Arduino Nano",
    class: "dip",
    dipPins: 30,
    description: "Nano seated across the gutter. Pin 1 is D1 (TX) at the USB end.",
    pins: dipPins([
      "D1",
      "D0",
      "RESET",
      "GND",
      "D2",
      "D3",
      "D4",
      "D5",
      "D6",
      "D7",
      "D8",
      "D9",
      "D10",
      "D11",
      "D12",
      "D13",
      "3V3",
      "AREF",
      "A0",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "5V",
      "RST",
      "GND",
      "VIN",
    ]),
  },
  {
    id: "pro-mini",
    name: "Arduino Pro Mini",
    class: "dip",
    dipPins: 24,
    description: "Pro Mini across the gutter. No USB; pin 1 is RAW / GND end toward the headers you solder.",
    pins: dipPins([
      "D1",
      "D0",
      "GND",
      "GND",
      "D2",
      "D3",
      "D4",
      "D5",
      "D6",
      "D7",
      "D8",
      "D9",
      "D10",
      "D11",
      "D12",
      "D13",
      "A0",
      "A1",
      "A2",
      "A3",
      "VCC",
      "RST",
      "GND",
      "RAW",
    ]),
  },
  {
    id: "attiny85",
    name: "ATtiny85",
    class: "dip",
    dipPins: 8,
    description: "8-pin AVR. Pin 1 is PB5 (RESET) at the notch.",
    pins: dipPins(["PB5", "PB3", "PB4", "GND", "PB0", "PB1", "PB2", "VCC"]),
  },
  {
    id: "pico",
    name: "Raspberry Pi Pico",
    class: "dip",
    dipPins: 40,
    description: "Pico seated across the gutter. Pin 1 is GP0 at the USB end. Needs a half or full board.",
    pins: dipPins([
      "GP0",
      "GP1",
      "GND",
      "GP2",
      "GP3",
      "GP4",
      "GP5",
      "GND",
      "GP6",
      "GP7",
      "GP8",
      "GP9",
      "GND",
      "GP10",
      "GP11",
      "GP12",
      "GP13",
      "GND",
      "GP14",
      "GP15",
      "GP16",
      "GP17",
      "GND",
      "GP18",
      "GP19",
      "GP20",
      "GP21",
      "GND",
      "GP22",
      "RUN",
      "GP26",
      "GP27",
      "GND",
      "GP28",
      "ADC_VREF",
      "3V3",
      "3V3_EN",
      "GND",
      "VSYS",
      "VBUS",
    ]),
  },
  {
    id: "pico-w",
    name: "Raspberry Pi Pico W",
    class: "dip",
    dipPins: 40,
    description: "Pico W, same breadboard pinout as Pico. Pin 1 is GP0 at the USB end.",
    pins: dipPins([
      "GP0",
      "GP1",
      "GND",
      "GP2",
      "GP3",
      "GP4",
      "GP5",
      "GND",
      "GP6",
      "GP7",
      "GP8",
      "GP9",
      "GND",
      "GP10",
      "GP11",
      "GP12",
      "GP13",
      "GND",
      "GP14",
      "GP15",
      "GP16",
      "GP17",
      "GND",
      "GP18",
      "GP19",
      "GP20",
      "GP21",
      "GND",
      "GP22",
      "RUN",
      "GP26",
      "GP27",
      "GND",
      "GP28",
      "ADC_VREF",
      "3V3",
      "3V3_EN",
      "GND",
      "VSYS",
      "VBUS",
    ]),
  },
  {
    id: "pi4",
    name: "Raspberry Pi 4",
    class: "module",
    description: "Off-board Pi 4. Bring 3V3/5V/GND and a few GPIOs over with Dupont wire.",
    pins: header(["3V3", "5V", "GND", "GPIO2", "GPIO3", "GPIO4", "GPIO17", "GPIO27", "GPIO22", "GPIO18", "GPIO23", "GPIO24", "GPIO25"]),
  },
  {
    id: "pi5",
    name: "Raspberry Pi 5",
    class: "module",
    description: "Off-board Pi 5. 40-pin header is the same map as Pi 4 for these pins.",
    pins: header(["3V3", "5V", "GND", "GPIO2", "GPIO3", "GPIO4", "GPIO17", "GPIO27", "GPIO22", "GPIO18", "GPIO23", "GPIO24", "GPIO25"]),
  },
  {
    id: "esp32",
    name: "ESP32 DevKit",
    class: "dip",
    dipPins: 30,
    description: "30-pin ESP32-WROOM DevKit across the gutter. Pin 1 is 3V3 at the USB end.",
    pins: dipPins([
      "3V3",
      "EN",
      "SVP",
      "SVN",
      "IO34",
      "IO35",
      "IO32",
      "IO33",
      "IO25",
      "IO26",
      "IO27",
      "IO14",
      "IO12",
      "GND",
      "IO13",
      "IO15",
      "IO2",
      "IO0",
      "IO4",
      "IO16",
      "IO17",
      "IO5",
      "IO18",
      "IO19",
      "GND",
      "IO21",
      "RX0",
      "TX0",
      "IO22",
      "VIN",
    ]),
  },
  {
    id: "esp32-s3",
    name: "ESP32-S3 DevKit",
    class: "module",
    description: "Off-board ESP32-S3. Pinouts vary; these are the usual power and UART pins.",
    pins: header(["3V3", "GND", "5V", "TX", "RX", "IO1", "IO2", "IO4", "IO5", "IO6", "IO7"]),
  },
  {
    id: "esp32-c3",
    name: "XIAO ESP32-C3",
    class: "dip",
    dipPins: 14,
    description: "Seeed XIAO ESP32-C3 across the gutter. Pin 1 is D0 at the USB end.",
    pins: dipPins(["D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "3V3", "GND", "5V"]),
  },
  {
    id: "nodemcu",
    name: "NodeMCU ESP8266",
    class: "module",
    description: "Off-board NodeMCU. 3V3 board; VIN is the USB 5 V pin.",
    pins: header(["3V3", "GND", "VIN", "D0", "D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8", "RX", "TX", "A0"]),
  },
  {
    id: "microbit",
    name: "micro:bit",
    class: "module",
    description: "Off-board BBC micro:bit. Edge connector broken out with Dupont leads.",
    pins: header(["3V", "GND", "P0", "P1", "P2", "P8", "P13", "P14", "P15", "P16"]),
  },
  {
    id: "teensy40",
    name: "Teensy 4.0",
    class: "module",
    description: "Off-board Teensy 4.0. 3.3 V I/O only.",
    pins: header(["3V3", "GND", "VIN", "0", "1", "2", "3", "13", "14", "15"]),
  },
];

const BY_ID = new Map(CATALOG.map((p) => [p.id, p]));

export function getPart(id: string): PartDef | undefined {
  return BY_ID.get(id);
}

export function searchParts(query: string): PartDef[] {
  const q = query.trim().toLowerCase();
  if (!q) return CATALOG;
  return CATALOG.filter(
    (p) =>
      p.id.includes(q) ||
      p.name.toLowerCase().includes(q) ||
      p.class.includes(q) ||
      p.description.toLowerCase().includes(q),
  );
}

export const CLASS_LABEL: Record<PartDef["class"], string> = {
  dip: "Chips",
  power: "Power",
  module: "Boards",
  passive: "Passives",
  led: "LEDs",
  switch: "Switches",
  button: "Buttons",
  sensor: "Sensors",
};

export const CLASS_ORDER: PartDef["class"][] = [
  "dip",
  "power",
  "module",
  "passive",
  "led",
  "switch",
  "button",
  "sensor",
];

